# Your Name or Company
title: Casper Welzel Andersen

# Description of your website. This is used for social sharing.
description: Website of Casper Welzel Andersen.

# Add your social links
social:
  - platform: github
    url: https://github.com/CasperWA
    name: GitHub
  - platform: linkedin
    url: https://linkedin.com/in/casperwa
    name: LinkedIn
  - platform: envelope
    url: "mailto:casper+website@welzel.nu"
    name: E-mail
  - platform: facebook
    url: https://facebook.com/casperwa
    name: Facebook
  # - platform: twitter
  #   url: casperwa
  #   name: Twitter

# General settings
url: https://casper.welzel.nu
# baseurl: /
markdown: kramdown
sharing_image: share.jpg
# google_analytics: UA-167986870-1

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
